import Head from 'next/head'
//import { useState, useEffect } from 'react';
import { OperationComponent } from '../components/operation';
import { OperationObject } from '../api/operation';
import { FsOsFileInfo } from '../api/fs';
// let init = false;
//let add = true;

export default function Index() {
   const x = {
        ID: "asd",
        Owner: "fas",
        Destination: "/media/flash/ok",
        Index: 0,
        Sources: [
          {
            name: "ok",
            size: 1600,
            path: "/media/src/ok",
            mode: 755,
            modTime: new Date().toISOString(),
          }
        ] as FsOsFileInfo[],
        status: 0,
  } as OperationObject

  return (
    <div>
      <Head>
        <title>ft - home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <OperationComponent {...x} />
    </div>
  )
}
